---
- hosts: database
  handlers:
   - name: restart mariadb 
     service:
      name: mariadb
      state: restarted
     become: yes
  tasks:
      - name: 'Instala banco de dados'
        yum:
          name: ['mariadb-server', 'python3-pip', 'python3-PyMySQL']
          state: latest
        become: yes
      - name: ativando o mariadb
        service:
          name: mariadb
          enabled: yes
        become: yes
      - name: inicializando mariadb
        service:
          name: mariadb
          state: started
        become: yes
      - name: 'Criando o banco do wordpress'
        mysql_db:
          name: "{{wp_db_name}}"
          login_user: root
          state: present

      - name: 'Criando o usuário do Mariadb'
        mysql_user:
          login_user: root
          name: "{{ wp_username }}"
          password: "{{ wp_user_password }}"
          priv: "{{ wp_db_name }}.*:ALL"
          state: present
          host: "{{ item }}"
        with_items:
         - 'localhost'
         - '127.0.0.1'
         - "{{wp_host_ip}}"

      - name: 'configurando mariadb para aceitar conexões remota'
        copy:
          src: '~/Documentos/ansible_aws/files/my.cnf'
          dest: '/etc/my.cnf.d/mariadb-server.cnf'
        become: yes
        notify:
         - restart mariadb


- hosts: wordpress
  handlers:
   - name: restart apache
     service:
      name: httpd
      state: restarted
     become: yes
  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      yum:
        name: ['httpd', 'php','php-mysqlnd', 'php-pdo', 'php-gd', 'php-mbstring', 'php-fpm','python3-pip', 'python3-PyMySQL']
        state: latest
      become: yes
    - name: Ativando o apache
      service:
        name: httpd
        enabled: yes
      become: yes
    - name: 'Baixa o arquivo de instalacao do wordpress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
    
    - name: 'Descompactar o wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www/html/'
        remote_src: yes
      become: yes

      
    - name: Copiando o arquivo de configuração
      copy:
        src: "{{ wp_installation_dir }}/wp-config-sample.php"
        dest: "{{ wp_installation_dir }}/wp-config.php"
        remote_src: yes
      become: yes

    - name: 'configura o wp-config com as entradas do banco de dados'
      replace:
        path: "{{ wp_installation_dir }}/wp-config.php"
        regexp: "{{item.regex}}"
        replace: "{{item.value}}"
      become: yes
      with_items:
         - {regex: 'database_name_here', value: "{{ wp_db_name }}"}
         - {regex: 'username_here', value: "{{ wp_username }}"}
         - {regex: 'password_here', value: "{{ wp_user_password }}"}
         - {regex: 'localhost', value: "{{ wp_db_ip}}"}

    - name: configura apache para servir o wordpress
      template:
        src: ~/Documentos/ansible_aws/templates/000-default.conf.j2
        dest: /etc/httpd/conf.d/wordpress.conf
        remote_src: no
      become: yes
      notify:
        - restart apache