---
- hosts: wordpress
  handlers:
   - name: restart apache
     service:
      name: httpd
      state: restarted
     become: yes
  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      yum:
        name: ['httpd', 'php','php-mysqlnd', 'php-pdo', 'php-gd', 'php-mbstring', 'php-fpm', 'mariadb-server', 'python3-pip', 'python3-PyMySQL']
        state: latest
      become: yes

    - name: 'Criando o banco do mysql'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present

    - name: 'Criando o usuário do mysql'
      mysql_user:
        login_user: root
        name: worldpress_user
        password: 12345
        priv: 'wordpress_db.*:ALL'
        state: present

    - name: 'Baixa o arquivo de instalacao do wordpress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
    
    - name: 'Descompactar o wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www/html/'
        remote_src: yes
      become: yes

      
    - name: Copiando o arquivo de configuração
      copy:
        src: /var/www/html/wordpress/wp-config-sample.php
        dest: /var/www/html/wordpress/wp-config.php
        remote_src: yes
      become: yes

    - name: 'configura o wp-config com as entradas do banco de dados'
      replace:
        path: /var/www/html/wordpress/wp-config.php
        regexp: "{{item.regex}}"
        replace: "{{item.value}}"
      become: yes
      with_items: 
         - {regex: 'database_name_here', value: 'wordpress_db'}
         - {regex: 'username_here', value: 'worldpress_user'}
         - {regex: 'password_here', value: '12345'}

    - name: configura apache para servir o wordpress
      copy:
        src: ~/Documentos/ansible_aws/files/000-default.conf
        dest: /etc/httpd/conf.d/wordpress.conf
        remote_src: no
      become: yes
      notify:
        - restart apache