---
- name: 'Baixa o arquivo de instalacao do wordpress'
  get_url:
    url: 'https://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'

- name: 'Descompactar o wordpress'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/html/'
    remote_src: yes
  become: yes

  
- name: Copiando o arquivo de configuração
  copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'configura o wp-config com as entradas do banco de dados'
  replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{item.regex}}"
    replace: "{{item.value}}"
  become: yes
  with_items:
      - {regex: 'database_name_here', value: "{{ wp_db_name }}"}
      - {regex: 'username_here', value: "{{ wp_username }}"}
      - {regex: 'password_here', value: "{{ wp_user_password }}"}
      - {regex: 'localhost', value: "{{ wp_db_ip}}"}

- name: configura apache para servir o wordpress
  template:
    src: ~/Documentos/ansible_aws/roles/wordpress/templates/000-default.conf.j2
    dest: /etc/httpd/conf.d/wordpress.conf
    remote_src: no
  become: yes
  notify:
    - restart apache