---
- name: 'Instala banco de dados'
  yum:
    name: ['mariadb-server', 'python3-pip', 'python3-PyMySQL']
    state: latest
  become: yes
- name: ativando o mariadb
  service:
    name: mariadb
    enabled: yes
  become: yes
- name: inicializando mariadb
  service:
    name: mariadb
    state: started
  become: yes
- name: 'Criando o banco do wordpress'
  mysql_db:
    name: "{{wp_db_name}}"
    login_user: root
    state: present

- name: 'Criando o usuário do Mariadb'
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - "{{wp_host_ip}}"

- name: 'configurando mariadb para aceitar conexões remota'
  copy:
    src: '~/Documentos/ansible_aws/roles/mysql/files/my.cnf'
    dest: '/etc/my.cnf.d/mariadb-server.cnf'
  become: yes
  notify:
    - restart mariadb

